### ISSUE TITLE
Error Deploying Component No base file for markup://c:utils

### ISSUE THREAD

**Issue by Harshad7** [jamessimone/lwc-paginator#1]
Getting the error  "No base file for markup://c:utils" while trying to deploy to a scratch org.

Looks like there is a name mismatch for the LWC component folder for utils.

utils
 - pagerUtils.js
 - pagerUtils.js-meta.xml

Changing the name of the utils folder to pagerUtils seemed to fix it. Let me know if you want me to create a PR .

Thanks

**Comment by jamessimone** [comment]
@Harshad7 all set! Thanks for reporting
